[theme]
base = "light"
primaryColor = "#625DF5"
backgroundColor = "#F5F6FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202331"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
